services:
  nginx:
    image: nginx:latest
    ports:
      - "5100:5100" # Expose Nginx on port 5100
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # Mount the Nginx configuration file
      - ./ssl:/etc/nginx/ssl:ro # Mount SSL certificates
    depends_on:
      - app # Ensure the app starts first
  app:
    build:
      context: . # Build context points to the current directory
    ports:
      - 5000:5000 # Expose the app on port 5000
    user: "${UID}"
